name: validate-frontend
on:
  pull_request:
    branches:
      - develop

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Download Repository
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0

      - name: Install dependencies
        run: npm install

      - name: Run E2E Tests
        uses: cypress-io/github-action@v5
        with:
          start: npm run start:staging
          wait-on: 'http://localhost:3000'
          browser: chrome
          record: false

      - name: Build
        run: npm run build:staging
